### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/estimate#19]
@strengejacke @pdwaggoner @mattansb @humanfactors @IndrajeetPatil 

I know it's summer and all, but if you wanna *really* relax at the beach, enjoying a nice Pina colada and a good read, I can only suggest the following vignettes, fresh out of the oven, showcasing some of the features of `estimate` 😁:

  - [**Data grids**](https://easystats.github.io/estimate/articles/data_grid.html)
  - [**Marginal means**](https://easystats.github.io/estimate/articles/marginal_means.html)
  - [**Contrast analysis**](https://easystats.github.io/estimate/articles/contrast_analysis.html)
  - [**Use a model to make predictions**](https://easystats.github.io/estimate/articles/predictions.html)
  - [**Describe non-linear
    curves**](https://easystats.github.io/estimate/articles/estimate_smooth.html)

In fact, for me this package is pretty much ready for a first release (right after parameters is accepted). Although supporting *mainly* rstanarm models, for now, once we have the API right it will be easy to extend (in fact, estimate_means and estimate_contrasts already support base/lme4 models 🤐).

Anyway, please do not hesitate to give your feedback on any aspects of the package!

**Comment by mattansb** [comment]
Looks really great!
Seeing as how these vignettes are very visual, was wondering... how could @strengejacke `ggeffects` fit into all of this? 🤔

**Comment by strengejacke** [comment]
After a quick look, I would say that the functions of ggeffects do what `estimate_response()` does with `data = "grid"`. `estimate_means()` is comparable to the *margins*-package, and `estimate_contrasts()` looks like what `emmeans::pairwise()` can do.

We've already thought of moving *ggeffects* over here to easystats (https://github.com/easystats/easystats/issues/15), but hesitated to do so because it did not fit perfectly into the scope back then, and it does not strictly follow the naming-conventions we have. But I do think that there'll be some overlap between *estimate* and *ggeffects*, and probably *estimate* can benefit from the experiences I have made with *ggeffects* ;-)

**Comment by DominiqueMakowski** [comment]
agreed and moreover, for now ggeffects supports 10000 times more packages... *for now* 😈
